"""add auto trade decision log

Revision ID: 1f0353de5e77
Revises: 927b7960af1d
Create Date: 2025-12-24 01:46:44.149830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0353de5e77'
down_revision: Union[str, Sequence[str], None] = '927b7960af1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_trade_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('signal', sa.String(), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('ma20', sa.Float(), nullable=True),
    sa.Column('ma50', sa.Float(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_trade_decisions_symbol'), 'auto_trade_decisions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_trade_decisions_symbol'), table_name='auto_trade_decisions')
    op.drop_table('auto_trade_decisions')
    # ### end Alembic commands ###
