"""add ml outcomes

Revision ID: de176b49dc2d
Revises: d98590ecf32a
Create Date: 2025-12-26 00:36:28.039642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de176b49dc2d'
down_revision: Union[str, Sequence[str], None] = 'd98590ecf32a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('horizon_minutes', sa.Integer(), nullable=True),
    sa.Column('future_return', sa.Float(), nullable=True),
    sa.Column('max_favorable_move', sa.Float(), nullable=True),
    sa.Column('max_adverse_move', sa.Float(), nullable=True),
    sa.Column('outcome_label', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['ml_feature_snapshot.snapshot_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_outcomes_snapshot_id'), 'ml_outcomes', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_outcomes_snapshot_id'), table_name='ml_outcomes')
    op.drop_table('ml_outcomes')
    # ### end Alembic commands ###
