"""add_guest_id_to_users

Revision ID: e75ceec56cfd
Revises: 6499225b2a00
Create Date: 2026-08-14 13:06:18.941402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75ceec56cfd'
down_revision: Union[str, Sequence[str], None] = '6499225b2a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('guest_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_guest_id'), 'users', ['guest_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_guest_id'), table_name='users')
    op.drop_column('users', 'guest_id')
    # ### end Alembic commands ###
