"""initial schema

Revision ID: ee78420b7973
Revises: 
Create Date: 2026-01-06 03:27:06.915786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee78420b7973'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_trade_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('signal', sa.String(), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('ma20', sa.Float(), nullable=True),
    sa.Column('ma50', sa.Float(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_trade_decisions_symbol'), 'auto_trade_decisions', ['symbol'], unique=False)
    op.create_table('ml_feature_snapshot',
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('snapshot_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('return_1d', sa.Float(), nullable=True),
    sa.Column('return_5d', sa.Float(), nullable=True),
    sa.Column('ma20', sa.Float(), nullable=True),
    sa.Column('ma50', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('rsi_slope', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('atr_percent', sa.Float(), nullable=True),
    sa.Column('rule_trend_ok', sa.Boolean(), nullable=True),
    sa.Column('rule_rsi_ok', sa.Boolean(), nullable=True),
    sa.Column('rule_volume_ok', sa.Boolean(), nullable=True),
    sa.Column('rule_volatility_ok', sa.Boolean(), nullable=True),
    sa.Column('rules_passed', sa.Boolean(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_ml_feature_snapshot_symbol'), 'ml_feature_snapshot', ['symbol'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ml_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('horizon_minutes', sa.Integer(), nullable=True),
    sa.Column('future_return', sa.Float(), nullable=True),
    sa.Column('max_favorable_move', sa.Float(), nullable=True),
    sa.Column('max_adverse_move', sa.Float(), nullable=True),
    sa.Column('outcome_label', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['ml_feature_snapshot.snapshot_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_outcomes_snapshot_id'), 'ml_outcomes', ['snapshot_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_table('rule_engine_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('rule_trend_ok', sa.Boolean(), nullable=True),
    sa.Column('rule_rsi_ok', sa.Boolean(), nullable=True),
    sa.Column('rule_volume_ok', sa.Boolean(), nullable=True),
    sa.Column('rule_volatility_ok', sa.Boolean(), nullable=True),
    sa.Column('rules_passed', sa.Boolean(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('blocked_by', sa.JSON(), nullable=True),
    sa.Column('explanations', sa.JSON(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['ml_feature_snapshot.snapshot_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('rule_engine_results')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_ml_outcomes_snapshot_id'), table_name='ml_outcomes')
    op.drop_table('ml_outcomes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ml_feature_snapshot_symbol'), table_name='ml_feature_snapshot')
    op.drop_table('ml_feature_snapshot')
    op.drop_index(op.f('ix_auto_trade_decisions_symbol'), table_name='auto_trade_decisions')
    op.drop_table('auto_trade_decisions')
    # ### end Alembic commands ###
